# Generated by Django 4.2.7 on 2025-12-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lab_test_recommendations',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('dosage_form', models.CharField(blank=True, max_length=50)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospitals.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.patient')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_medicines',
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='medicines_name_017048_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active'], name='medicines_is_acti_508f30_idx'),
        ),
        migrations.AddField(
            model_name='labtestrecommendation',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='prescriptions.prescription'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionmedicine',
            unique_together={('prescription', 'medicine')},
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'created_at'], name='prescriptio_patient_50dfd5_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'created_at'], name='prescriptio_doctor__2c554b_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestrecommendation',
            index=models.Index(fields=['prescription', 'is_completed'], name='lab_test_re_prescri_292274_idx'),
        ),
    ]
