# Generated by Django 4.2.7 on 2025-12-29 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '__first__'),
        ('appointments', '0003_appointmentqueue_and_more'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='emr_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='emr.emrrecord'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment'),
        ),
    ]
