# Generated by Django 4.2.7 on 2025-12-29 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_bed_department_doctorapplication_emergencycapacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(choices=[('OPD', 'OPD'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('queue_number', models.IntegerField()),
                ('estimated_wait_time', models.IntegerField(default=0)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appointment_queues',
            },
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_hospita_5b3b23_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('OPD', 'OPD'), ('TELE_CONSULT', 'Tele-consultation'), ('EMERGENCY', 'Emergency'), ('LAB_TEST', 'Lab Test'), ('FOLLOW_UP', 'Follow-up'), ('HOME_VISIT', 'Home Visit')], default='OPD', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospitals.department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='operations_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OPERATIONS_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospitals.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('REVIEWED', 'Reviewed by Operations'), ('ASSIGNED', 'Assigned to Doctor'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BILLED', 'Billed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='REQUESTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'appointment_date', 'appointment_time'], name='appointment_hospita_125dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['reviewed_by', 'status'], name='appointment_reviewe_1ac31b_idx'),
        ),
        migrations.AddField(
            model_name='appointmentqueue',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentqueue',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='hospitals.hospital'),
        ),
        migrations.AddIndex(
            model_name='appointmentqueue',
            index=models.Index(fields=['hospital', 'queue_type', 'queue_number'], name='appointment_hospita_25c9f2_idx'),
        ),
    ]
