# Generated by Django 4.2.7 on 2025-12-29 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('bed_type', models.CharField(choices=[('GENERAL', 'General'), ('ICU', 'ICU'), ('NICU', 'NICU'), ('HDU', 'HDU'), ('ISOLATION', 'Isolation')], max_length=20)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'beds',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'doctor_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.IntegerField(default=0)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('wait_time_minutes', models.IntegerField(default=0)),
                ('ventilators_available', models.IntegerField(default=0)),
                ('ventilators_total', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emergency_capacity',
            },
        ),
        migrations.CreateModel(
            name='OperationTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ot_number', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operation_theaters',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hospital',
            name='director',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'HOSPITAL_DIRECTOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='opd_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='operations_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OPERATIONS_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hospitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='subscription_tier',
            field=models.CharField(default='BASIC', max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='admin',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'HOSPITAL_ADMIN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['opd_open', 'emergency_available'], name='hospitals_opd_ope_272f76_idx'),
        ),
        migrations.AddField(
            model_name='operationtheater',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_theaters', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='emergencycapacity',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_capacity', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='hospitals.department'),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_applications', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='bed',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospitals.department'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['department', 'is_active'], name='doctors_departm_d72b64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operationtheater',
            unique_together={('hospital', 'ot_number')},
        ),
        migrations.AddIndex(
            model_name='doctorapplication',
            index=models.Index(fields=['hospital', 'status'], name='doctor_appl_hospita_3cc038_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorapplication',
            index=models.Index(fields=['user', 'status'], name='doctor_appl_user_id_a0fa97_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorapplication',
            index=models.Index(fields=['status', 'applied_at'], name='doctor_appl_status_822cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['hospital', 'is_active'], name='departments_hospita_6fbe59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'name')},
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['hospital', 'bed_type', 'is_available'], name='beds_hospita_56d331_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('hospital', 'bed_number')},
        ),
    ]
