# Generated by Django 4.2.7 on 2025-12-29 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'LAB_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['lab', 'status'], name='lab_test_re_lab_id_f7b978_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['status', 'requested_at'], name='lab_test_re_status_3423a6_idx'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['report_date'], name='lab_reports_report__21026a_idx'),
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['name', 'city'], name='labs_name_e6985f_idx'),
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['is_active', 'is_approved'], name='labs_is_acti_602f17_idx'),
        ),
    ]
