# Generated by Django 4.2.7 on 2025-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HOSPITAL_DIRECTOR', 'Hospital Director'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('HOSPITAL_ADMIN', 'Hospital Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('MEDICAL_ASSISTANT', 'Medical Assistant'), ('LAB_MANAGER', 'Lab Manager'), ('LAB_TECHNICIAN', 'Lab Technician'), ('PHARMACY_MANAGER', 'Pharmacy Manager'), ('DELIVERY_EXECUTIVE', 'Delivery Executive'), ('PATIENT', 'Patient'), ('CAREGIVER', 'Caregiver')], max_length=20),
        ),
    ]
