# Generated by Django 4.2.7 on 2025-12-29 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'PHARMACY_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='pharmacy.pharmacyorder'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacyorderitem',
            unique_together={('order', 'prescription_medicine')},
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['pharmacy', 'status'], name='pharmacy_or_pharmac_d18271_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['prescription', 'status'], name='pharmacy_or_prescri_7f2ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyorder',
            index=models.Index(fields=['status', 'created_at'], name='pharmacy_or_status_7291c8_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacymedicine',
            index=models.Index(fields=['pharmacy', 'is_available'], name='pharmacy_me_pharmac_0b0270_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacymedicine',
            index=models.Index(fields=['medicine', 'is_available'], name='pharmacy_me_medicin_9d91ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacymedicine',
            unique_together={('pharmacy', 'medicine')},
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['name', 'city'], name='pharmacies_name_38e60b_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['is_active', 'is_approved'], name='pharmacies_is_acti_6d597d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_invoice_e14adb_idx'),
        ),
    ]
