# Generated by Django 4.2.7 on 2025-12-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='pharmacy_in_invoice_4dbe8d_idx',
            old_name='invoices_invoice_7778bc_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='pharmacy_in_invoice_7700cb_idx',
            old_name='invoices_invoice_e14adb_idx',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='pharmacy_invoices',
        ),
    ]
